version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: barbershop-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barbershop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barbershop-network

volumes:
  postgres_data:

networks:
  barbershop-network:
    driver: bridge 